### ISSUE TITLE
Wrong evaluation of ((0x7fffffffffffffffL * 2UL) < 0)

### ISSUE THREAD

**Issue by danmar** [danmar/simplecpp#207]
Reported here:
https://sourceforge.net/p/cppcheck/discussion/development/thread/c101b0d84d/

expressions in `#if` might be evaluated wrongly.

**Comment by keinflue** [comment]
I have seen a similar issue and would like to fix it. My idea is to replace all uses of `long long` for numeric values by a tagged union of `long long` and `unsigned long long` with operators overloaded to adhere to the usual arithmetic conversion rules. I think this should be sufficient to have standard-compliant arithmetics in the preprocessor as long as the target plaformt doesn't have integer types larger than the host's `(unsigned) long long`. Is that a direction you would approve of?

**Comment by danmar** [comment]
> My idea is to replace all uses of long long for numeric values by a tagged union of long long and unsigned long long with operators overloaded to adhere to the usual arithmetic conversion rules by using the behavior of the host. 

I think that is a good idea. We have discussed adding such union/class in Cppcheck also to replace the `Mathlib::bigint`. So well if it could be reused that would be good.

> usual arithmetic conversion rules by using the behavior of the host.

ideally I think the typesizes should be configurable at runtime. to start with feel free to put some constants in the code that match the host i.e. `const int sizeofInt = sizeof(int)`. and then we can look at how to configure those values later..

if you detect ub feel free to throw exceptions.

**Comment by keinflue** [comment]
@danmar

> We have discussed adding such union/class in Cppcheck also to replace the Mathlib::bigint. So well if it could be reused that would be good.

> ideally I think the typesizes should be configurable. to start with feel free to put some constants in the code that match the host i.e. const int sizeofInt = sizeof(int). and then we can look at how to configure those values later..

For the preprocessor there doesn't need to be any specification for the size of `int`, only for the size of `intmax_t` (i.e. the largest integral type according to the standard definition). As far as I can tell the standards say that the preprocessor operates only in this type plus it's unsigned variant. I am not sure that there is any platform where this is not 64bits wide. Most platforms also share the other implementation-defined behaviors such as two's complement and arithmetic right-shift of negative values etc., so I think for most platforms there is no configuration required for the preprocessor arithmetic.

For the use in the actual compilation phases the different types need to be distinguished to get the correct conversion behavior, but that makes it much more complicated. During compilation compilers also offer types larger than `intmax_t`, e.g. GCC's `__int128`, which you might want to support. So I think it might be better to use arbitrary-length integers in cppcheck instead, either using one of the specialized libraries out there or implementing a simple/naive one in cppcheck itself.

For now, my intention was to prepare a PR that only differentiates `long long` and `unsigned long long` and none of the other types since the latter would be much more work.

**Comment by danmar** [comment]
> For the preprocessor there doesn't need to be any specification for the size of int, only for the size of intmax_t (i.e. the largest integral type according to the standard definition). As far as I can tell the standards say that the preprocessor operates only in this type plus it's unsigned variant.

ok

**Comment by firewave** [comment]
```
simplecpp.cpp:1157:20: runtime error: signed integer overflow: 9223372036854775807 * 2 cannot be represented in type 'long long int'
    #0 0x55f7aa7e34b5 in simplecpp::TokenList::constFoldMulDivRem(simplecpp::Token*) /home/user/CLionProjects/simplecpp/simplecpp.cpp:1157
    #1 0x55f7aa7e908b in simplecpp::TokenList::constFold() /home/user/CLionProjects/simplecpp/simplecpp.cpp:953
    #2 0x55f7aa7eedc4 in evaluate /home/user/CLionProjects/simplecpp/simplecpp.cpp:2955
    #3 0x55f7aa81059e in simplecpp::preprocess(simplecpp::TokenList&, simplecpp::TokenList const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, simplecpp::FileDataCache&, simplecpp::DUI const&, std::__cxx11::list<simplecpp::Output, std::allocator<simplecpp::Output> >*, std::__cxx11::list<simplecpp::MacroUsage, std::allocator<simplecpp::MacroUsage> >*, std::__cxx11::list<simplecpp::IfCond, std::allocator<simplecpp::IfCond> >*) /home/user/CLionProjects/simplecpp/simplecpp.cpp:3647
    #4 0x55f7aa7bd536 in main /home/user/CLionProjects/simplecpp/main.cpp:166
    #5 0x7fda65c27674  (/usr/lib/libc.so.6+0x27674) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)
    #6 0x7fda65c27728 in __libc_start_main (/usr/lib/libc.so.6+0x27728) (BuildId: 4fe011c94a88e8aeb6f2201b9eb369f42b4a1e9e)
    #7 0x55f7aa7c19c4 in _start (/home/user/CLionProjects/simplecpp/simplecpp+0xd89c4) (BuildId: c7089bfc11f7bcc19a5f9dfd1f8dc21b3d5c1413)
```
