### ISSUE TITLE
UB in simplecpp::preprocess with garbage-#include 

### ISSUE THREAD

**Issue by matthiaskrgr** [danmar/simplecpp#21]
this code from gcc tests
````c
#include /\
````
causes UB:
````
externals/simplecpp/simplecpp.cpp:1559:72: runtime error: unsigned integer overflow: 1 - 2 cannot be represented in type 'unsigned long'
externals/simplecpp/simplecpp.cpp:1681:96: runtime error: unsigned integer overflow: 1 - 2 cannot be represented in type 'unsigned long'
````

with stacktrace:
````
Checking foo.c...
externals/simplecpp/simplecpp.cpp:1559:72: runtime error: unsigned integer overflow: 1 - 2 cannot be represented in type 'unsigned long'
    #0 0x16d9920 in simplecpp::load(simplecpp::TokenList const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, simplecpp::DUI const&, std::__cxx11::list<simplecpp::Output, std::allocator<simplecpp::Output> >*) /home/matthias/vcs/github/cppcheck_llvm_debug/externals/simplecpp/simplecpp.cpp:1559:72
    #1 0x115e3c3 in Preprocessor::loadFiles(simplecpp::TokenList const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /home/matthias/vcs/github/cppcheck_llvm_debug/lib/preprocessor.cpp:420:18
    #2 0xf7d633 in CppCheck::processFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::istream&) /home/matthias/vcs/github/cppcheck_llvm_debug/lib/cppcheck.cpp:108:22
    #3 0xf7a5cf in CppCheck::check(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/cppcheck_llvm_debug/lib/cppcheck.cpp:74:12
    #4 0x8538eb in CppCheckExecutor::check_internal(CppCheck&, int, char const* const*) /home/matthias/vcs/github/cppcheck_llvm_debug/cli/cppcheckexecutor.cpp:820:41
    #5 0x84e45c in CppCheckExecutor::check(int, char const* const*) /home/matthias/vcs/github/cppcheck_llvm_debug/cli/cppcheckexecutor.cpp:185:16
    #6 0x88b999 in main /home/matthias/vcs/github/cppcheck_llvm_debug/cli/main.cpp:136:21
    #7 0x7f2871423730 in __libc_start_main (/lib64/libc.so.6+0x20730)
    #8 0x730478 in _start (/home/matthias/vcs/github/cppcheck_llvm_debug/cppcheck+0x730478)

SUMMARY: AddressSanitizer: undefined-behavior externals/simplecpp/simplecpp.cpp:1559:72 in 
externals/simplecpp/simplecpp.cpp:1681:96: runtime error: unsigned integer overflow: 1 - 2 cannot be represented in type 'unsigned long'
    #0 0x16ee896 in simplecpp::preprocess(simplecpp::TokenList&, simplecpp::TokenList const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, simplecpp::TokenList*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, simplecpp::TokenList*> > > const&, simplecpp::DUI const&, std::__cxx11::list<simplecpp::Output, std::allocator<simplecpp::Output> >*, std::__cxx11::list<simplecpp::MacroUsage, std::allocator<simplecpp::MacroUsage> >*) /home/matthias/vcs/github/cppcheck_llvm_debug/externals/simplecpp/simplecpp.cpp:1681:96
    #1 0x1151115 in Preprocessor::getcode(simplecpp::TokenList const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, bool) /home/matthias/vcs/github/cppcheck_llvm_debug/lib/preprocessor.cpp:488:5
    #2 0xf8603b in CppCheck::processFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::istream&) /home/matthias/vcs/github/cppcheck_llvm_debug/lib/cppcheck.cpp:202:47
    #3 0xf7a5cf in CppCheck::check(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/matthias/vcs/github/cppcheck_llvm_debug/lib/cppcheck.cpp:74:12
    #4 0x8538eb in CppCheckExecutor::check_internal(CppCheck&, int, char const* const*) /home/matthias/vcs/github/cppcheck_llvm_debug/cli/cppcheckexecutor.cpp:820:41
    #5 0x84e45c in CppCheckExecutor::check(int, char const* const*) /home/matthias/vcs/github/cppcheck_llvm_debug/cli/cppcheckexecutor.cpp:185:16
    #6 0x88b999 in main /home/matthias/vcs/github/cppcheck_llvm_debug/cli/main.cpp:136:21
    #7 0x7f2871423730 in __libc_start_main (/lib64/libc.so.6+0x20730)
    #8 0x730478 in _start (/home/matthias/vcs/github/cppcheck_llvm_debug/cppcheck+0x730478)
````

**Comment by danmar** [comment]
strange error message from clang. as far as I know unsigned overflows are not UB.

**Comment by danmar** [comment]
hmm.. unsigned overflow is not UB. is it possible to get some strange behaviour? I don't see how I can write a regression test for this.

**Comment by danmar** [comment]
Btw.. I just get this output:

    $ ./simplecpp 21.c 
    
    21.c:1: missing header: Header not found: /

Compiled with makefile.
