### ISSUE TITLE
Segmentation fault on empty macro after layers of expansion at simplecpp::Macro::expand()

### ISSUE THREAD

**Issue by Barro** [danmar/simplecpp#49]
Following code causes simpleccp to segmentation fault at simplecpp::Macro::expand():

```
#define f()
#define g f
#define t(a) a
(t (g))
```

It results in following GDB stack backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
simplecpp::Macro::expand (this=..., output=..., loc=..., nameToken=..., macros=..., expandedmacros=...) at simplecpp.cpp:1270
1270                if (tok->op != '#') {
(gdb) bt
#0  simplecpp::Macro::expand (this=..., output=..., loc=..., nameToken=..., macros=..., expandedmacros=...) at simplecpp.cpp:1270
#1  0x0000000000418d3b in simplecpp::Macro::expand (this=..., output=..., rawtok=..., macros=..., files=...) at simplecpp.cpp:965
#2  0x000000000040cdbe in preprocessToken (output=..., tok1=..., macros=..., files=..., outputList=...) at simplecpp.cpp:1858
#3  0x0000000000410e1d in simplecpp::preprocess (output=..., rawtokens=..., files=..., filedata=..., dui=..., outputList=..., macroUsage=...) at simplecpp.cpp:2153
#4  0x00000000004040fd in main (argc=..., argv=...) at main.cpp:60
(gdb) list
1265
1266            Token * const output_end_1 = output->back();
1267
1268            // expand
1269            for (const Token *tok = valueToken; tok != endToken;) {
1270                if (tok->op != '#') {
1271                    // A##B => AB
1272                    if (tok->next && tok->next->op == '#' && tok->next->next && tok->next->next->op == '#') {
1273                        if (!sameline(tok, tok->next->next->next))
1274                            throw invalidHashHash(tok->location, name());
```

This happens with simplecpp revision 1e9149fe3a6ade84d38628488a73cc6d914d174d

**Comment by Barro** [comment]
Although this happens in the same function as in issue #48, the code that makes it happen looks different and also line numbers differ.

**Comment by hexcoder-** [comment]
here is a simpler test case
```
#define f()
#define t(a) a
(t (f))
```
